//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LI_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatientRequest
    {
        public string FullName { get; set; }
        public string JMBG { get; set; }
        public string InsuranceCardNumber { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public string ReasonOfRequest { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> EmergencyReq { get; set; }
        public int PatientID { get; set; }
        public int RequestID { get; set; }
    }
}
